Update final.yml

diff --git a/.github/workflows/final.yml b/.github/workflows/final.yml
--- a/.github/workflows/final.yml
+++ b/.github/workflows/final.yml
@@ -118,17 +118,18 @@ jobs:
         run: |
           set -e
           git fetch origin
-
+          
+          source $GITHUB_ENV
           MERGE_BASE=$DEFAULT_BRANCH
           BRANCHES=($(echo "${{ steps.resolve_branches.outputs.branches }}" | tr ',' ' '))
 
           git checkout -b dry-$MERGE_BASE origin/$MERGE_BASE
-          git merge --no-commit --no-ff origin/${{ github.head_ref }} || echo "error_branch=$MERGE_BASE" >> $GITHUB_OUTPUT
+          git merge --no-commit --no-ff origin/${{ inputs.source_branch }} || echo "error_branch=$MERGE_BASE" >> $GITHUB_OUTPUT
 
           for TARGET in "${BRANCHES[@]}"; do
-            git checkout -b dry-$TARGET origin/$TARGET
-            git merge --no-commit --no-ff dry-$MERGE_BASE || echo "error_branch=$TARGET" >> $GITHUB_OUTPUT
-            MERGE_BASE=$TARGET
+           git checkout -b dry-$TARGET origin/$TARGET
+           git merge --no-commit --no-ff dry-$MERGE_BASE || echo "error_branch=$TARGET" >> $GITHUB_OUTPUT
+           MERGE_BASE=$TARGET
           done
         continue-on-error: true
 
